name: .NET Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore
      run: dotnet restore LittleSwitcher.csproj

    - name: Build
      run: dotnet build LittleSwitcher.csproj --configuration ${{ matrix.configuration }} --no-restore

    - name: Publish
      if: matrix.configuration == 'Release'
      run: dotnet publish LittleSwitcher.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true

    - name: Upload build artifacts
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: LittleSwitcher
        path: bin\Release\net9.0-windows10.0.19041.0\win-x64\publish\
